### ISSUE TITLE
 Feature Request: Availability of Pre-trained Encoder for sam_vit_h Scale

### ISSUE THREAD

**Issue by dianzizs** [zhiwen-xdu/EventSAM#10]
I'm working with your model and was wondering if there are plans to release a pre-trained encoder module for the sam_vit_h scale?

Would you happen to have any plans to offer this in the future, or is it something that might be considered? Any information you could provide on this matter would be greatly appreciated.

**Comment by zhiwen-xdu** [comment]
Sorry that our sam_vit_h.pt has been damaged and we don't have the resource enough to reproduce my code  at present, I think if you have 4 RTX3090 or more, you can easily reproduce that, if you have any problem, you can email me and I will try my best to solve that.
