### ISSUE TITLE
questions about folder "event_image"

### ISSUE THREAD

**Issue by suizhipeng** [zhiwen-xdu/EventSAM#12]
Thank you for your group's outstanding work. However, I have some questions regarding the dataset. In the released dataset, under `Event_seg_dataset/Datasets/RGBE-SEG/train/`, each folder contains `voxel_image/`, `event/`, and `rgb_image/`, but there is no `event_img/`. Based on your code, I assume that training primarily relies on `rgb_image` and `event_image`. Could you please provide the code for converting `event` data into `event_image`?
![图片](https://github.com/user-attachments/assets/e8961424-a2fd-4ada-ba73-c10b6f572427)

**Comment by suizhipeng** [comment]
Thank you for your excellent work, I noticed that the image used in the training is the 3-channel time-voxel image, could you provide the code to convert the raw event data into three-channel voxel? Thanks very much.

**Comment by zhiwen-xdu** [comment]
Thank you for your issues.  The training program primarily uses rgb_image and voxel_image, with event_image serving solely for event visualization. 
```Shell
├── event          # Event Source File： [N,4]-[x,y,t,p]
├── rgb_image      # RGB Images, which is the input of teacher network.
├── event_image    # Event-oriented Binary Images, which is used for event visualization.
├── voxel_image    # Event-oriented Voxel-like Images, which is the input of student network.
```

The event_image can be easily generated from event files (event/*.npz) using the following code:
```Shell
def ev2img(events):
    # events: [x,y,t,p]
    ev_img = 255*np.ones((260,346,3),dtype=np.uint8)
    N,_ = events.shape
    for i in range(N):
        x,y,p = int(events[i,0]),int(events[i,1]),int(events[i,3])
        if p == 0:
            ev_img[y,x,:] = np.array([200,30,30])  # blue
        elif p == 1:
            ev_img[y,x,:] = np.array([30,30,200])    # red
    return ev_img
```

**Comment by suizhipeng** [comment]
Thank you very much for your patience, I also want to ask how the voxel_image is constructed, could you provide the relevant code?  Thank you so much.

**Comment by zhiwen-xdu** [comment]
Q: Thank you for your excellent work, I noticed that the image used in the training is the 3-channel time-voxel image, could you provide the code to convert the raw event data into three-channel voxel? Thanks very much.

A: Thank you for your issues.  We use the code from https://github.com/TimoStoff/event_utils to convert event voxel grid. The three-channel voxel image can be easily generated from event files (event/*.npz) using the following code:
```Shell
from representations.event_voxel import *

events = np.load(npz_path)
xs, ys, ts, ps = events["x"], events["y"], events["t"], events["p"]
voxel = events_to_voxel(xs, ys, ts, ps, B=3, sensor_size=(260, 346), temporal_bilinear=True)  # voxel: [3,H,W]
voxel = voxel.transpose((1, 2, 0))

voxel = voxel - np.min(voxel)
voxel_img = 255 * (voxel / np.max(voxel))
cv2.imwrite(voxel_save_path, voxel_img)
```

**Comment by suizhipeng** [comment]
Thank you very much for your patience and excellent work!
