### ISSUE TITLE
Request about how to publish datasets

### ISSUE THREAD

**Issue by ryhara** [zhiwen-xdu/EventSAM#9]
I read your paper and am very interested in this research.

I want to run this GitHub code, but I'm having trouble downloading the dataset.
It looks like a Chinese phone number is required to download the dataset.
Could you share datasets via other tools, such as Google Drive?

I look forward to your reply.

**Comment by ryhara** [comment]
@ZHU-Zhiyu Thank you for your reply. I'm looking forward to it!

**Comment by ZHU-Zhiyu** [comment]
@ryhara Here is the [link ](https://portland-my.sharepoint.com/:f:/g/personal/zhiyuzhu2-c_my_cityu_edu_hk/Emi4O0IfE6ROgN5hgW0QXWQBuKWEM2vmjkbHfkBySsJwlg?e=ZsbIN1) with passwd:1234

**Comment by ryhara** [comment]
@ZHU-Zhiyu  Thank you very mach!
I was able to download it.

Could you please add the Pre-trained Model to the folder? Sorry for so many requests...

This part of the README.md
> ## Pre-trained Model
> Pre-trained EventSAM model (e.g. rgbe_encoder.pth) needs to be downloaded and put in ./checkpoints.
>
> [EventSAM Model](https://pan.baidu.com/s/1_srqKTBRESvD0jYDQiN_FQ) Code：1234

**Comment by ZHU-Zhiyu** [comment]
Hi @ryhara  I have uploaded the checkpoint in the same folder. You can check the [link](https://portland-my.sharepoint.com/:f:/g/personal/zhiyuzhu2-c_my_cityu_edu_hk/Emi4O0IfE6ROgN5hgW0QXWQBuKWEM2vmjkbHfkBySsJwlg?e=ZsbIN1)again.

**Comment by ryhara** [comment]
@ZHU-Zhiyu 
I was able to download it!
I really appreciate it. I will read the paper and the code again, and use it as a reference for my research! Thank you.
